### ISSUE TITLE
Providing array of integers to num_hidden and molecular_num_hidden doesn't work

### ISSUE THREAD

**Issue by W4RJ4** [CBIIT/NCI-DOE-Collab-Pilot2-Autoencoder_MD_Simulation_Data#2]
Looks like the parameters **molecular_num_hidden** and **num_hidden** do not except multiple values when provided through the command line. For example, command:

`python p2b1_baseline_keras2.py --num_hidden 512 32`

returns

`p2b1_baseline: error: unrecognized arguments: 32`

The command works when “‘default’: None” is deleted from parameter definition in p2b1.py.

**Comment by jonesse3** [comment]
@W4RJ4 Thanks for pointing this out! I removed default:None for both parameters.

**Comment by Chloe-Thangavelu** [comment]
> Looks like the parameters **molecular_num_hidden** and **num_hidden** do not except multiple values when provided through the command line. For example, command:
> 
> `python p2b1_baseline_keras2.py --num_hidden 512 32`
> 
> returns
> 
> `p2b1_baseline: error: unrecognized arguments: 32`
> 
> The command works when “‘default’: None” is deleted from parameter definition in p2b1.py.

Do you know if the eval_bool parameter is working?
