### ISSUE TITLE
Question? - Unused parameters

### ISSUE THREAD

**Issue by W4RJ4** [CBIIT/NCI-DOE-Collab-Pilot2-Autoencoder_MD_Simulation_Data#3]
These parameters:
- fig_bool
- data_set
- cool
- num_hidden
- weight_path
are defined in [p2b1.py](https://github.com/CBIIT/NCI-DOE-Collab-Pilot2-Autoencoder_MD_Simulation_Data/blob/main/Pilot2/P2B1/p2b1.py) but i cannot find where there are later used in the code. cool and num_hidden are defined as required inputs.

Also, the only mention of some of them seems to be commented out. [parameter_set.R](https://github.com/CBIIT/NCI-DOE-Collab-Pilot2-Autoencoder_MD_Simulation_Data/blob/3f8d4dc063d30a88b1f1e56ba44f41812e267cb3/Pilot2/P2B1/parameter_set.R) so if you can maybe shed a little bit more light on usage of these parameters.

Thank you

**Comment by jonesse3** [comment]
Hi @W4RJ4, thank you for pointing this out. It looks like the only parameter used was _data_set_ within [p2b1.py](https://github.com/CBIIT/NCI-DOE-Collab-Pilot2-Autoencoder_MD_Simulation_Data/blob/main/Pilot2/P2B1/p2b1.py). I believe at one point the developers of this resource may have used these parameters. To avoid further confusion in the future, I commented these out.
